### ISSUE TITLE
`TypeError: ESLint is not a constructor` if options are passed as a string (v1.4.3)

### ISSUE THREAD

**Issue by ascartabelli** [origin-1/gulp-eslint-new#5] opened 2022-05-19 09:09 UTC
I'm referring to [this destructuring](https://github.com/fasttime/gulp-eslint-new/blob/main/index.js#L117) that causes an error if a config file path string is passed as `options`.

**Comment by fasttime** [comment] 2022-05-19 09:43
I can't seem to reproduce this. What is the error you are getting?

**Comment by ascartabelli** [comment] 2022-05-19 09:46
> I can't seem to reproduce this. What is the error you are getting?

I'm getting `TypeError: ESLint is not a constructor`, because `ESLint` isn't getting a value [here](https://github.com/fasttime/gulp-eslint-new/blob/main/util.js#L334). 
Same applies for the other options mentioned above.

**Comment by fasttime** [comment] 2022-05-19 09:51
Got it. I'll be looking at that when I have a chance.

**Comment by ascartabelli** [comment] 2022-05-19 09:55
> Got it. I'll be looking at that when I have a chance.

Thanks a lot.
For others reading this: I forgot to add the obvious workaround, which is simply passing `{ overrideConfigFile: yourConfigPath }` as options.

**Comment by fasttime** [comment] 2022-05-19 18:08
Note that those undefined values in the destructuring assignment are fine. It's intended that `quiet` and `warnIgnored` could be `undefined`, even when an options object is passed as an argument.

But the `TypeError` about `ESLint` not being a constructor is a regression bug in version 1.4.3. Too bad that there was no test to catch it. It will be fixed in version 1.4.4. Thanks a lot for reporting this issue.

**Closed as completed** 2022-05-19 20:17 UTC
Labels: bug

**Comment by ascartabelli** [comment] 2022-05-20 07:05
> Thanks a lot for reporting this issue

You're very welcome!
